repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: Format Go code (make fmt)
        entry: make fmt
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-lint
        name: Lint Go code (make lint)
        entry: make lint
        language: system
        files: \.go$
        pass_filenames: false
