name: ci-pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5
          verify: false
      - run: make lint
      - run: make fmt
      - run: make test
